export const APP_ACTIONS = {
  SEARCH_MOVIES: 'app/SEARCH_MOVIES',
  SET_MOVIES: 'app/SET_MOVIES',
  FETCH_NEXT_MOVIES: 'app/FETCH_NEXT_MOVIES',
  ADD_MOVIES: 'app/ADD_MOVIES',
  SET_CURRENT_MOVIE: 'app/SET_CURRENT_MOVIE',
  SET_FULL_CURRENT_MOVIE: 'app/SET_FULL_CURRENT_MOVIE',
  ADD_FAVORITE_MOVIE: 'app/ADD_FAVORITE_MOVIE',
  REMOVE_FAVORITE_MOVIE: 'app/REMOVE_FAVORITE_MOVIE',
  SET_FAVORITE_MOVIES: 'app/SET_FAVORITE_MOVIES',

};
